### ISSUE TITLE
Any contribs you suggest to contribute?

### ISSUE THREAD

**Issue by macdavid313** [eudoxia0/lucerne#11]
Any contribs you suggest to contribute? Like a db contrib using `Crane`?

**Comment by eudoxia0** [comment]
I don't think there should be contribs for ORMs, those should be set up separately, in the interest of keeping this a **micro** framework.

One thing I'd like to do, but probably won't, since I don't have the time right now, is expand the `lucerne-auth` contrib and remake it along the lines of [flask-auth](https://pythonhosted.org/Flask-Auth/), which is a pretty well designed auth framework.

**Comment by macdavid313** [comment]
hmm... I see.

**Comment by gschjetne** [comment]
I was thinking something on the line of error handling. A middleware that handles signals and shows an appropriate error page, I already do something similar on my own with a Ningle app.

**Comment by eudoxia0** [comment]
https://github.com/eudoxia0/clack-errors is included by default
